backend:
  name: github
  repo: smbgood/banshee-web-content
media_folder: static/assets
public_folder: content/assets
collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }