backend:
  name: github
  repo: smbgood/banshee-web-content
#publish_mode:editorial_workflow
media_folder: "static/images/uploads"
public_folder: "images/uploads"
site_url: https://www.bansheebabe.com
display_url: https://www.bansheebabe.com
collections:
  - name: blog
    label: Blog
    folder: "content/blog"
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
      - { name: coverimage, label: Cover Image, widget: image }
      - { name: fullimage, label: Full Image, widget: image }
      - { name: product, label: Product to Link}
      - { name: glowcolor, label: Glow Color}
      - label: Attribution
        name: attribution
        widget: object
        fields:
          - {label: Image Title, name: attrTitle, widget: string, required: false}
          - {label: Author, name: attrAuthor, widget: string, required: false}
          - {label: Source URL, name: attrLink, widget: string, pattern:['.+', "Must fill out image source link at the very least"]}
          - {label: License, name: attrLicense, widget: string, required: false}
          - {label: Modifications, name: attrMods, widget: string, required: false}
  - name: categories
    label: Categories
    folder: "content/categories"
    create: true
    extension: json
    identifier_field: id
    fields:
      - { name: name, label: Name }
      - { name: id, label: Category ID }
      - { name: products, label: Products, widget: list }
      - { name: image, label: Image, widget: image}
  - name: butts
    label: Products
    folder: "content/butts"
    create: true
    extension: json
    identifier_field: id
    fields:
      - { name: name, label: Name }
      - { name: id, label: Product SKU ID }
      - { name: image, label: Image, widget: image}
  - name: siteadmin
    label: Site Admin
    folder: "content/siteadmin"
    create: true
    extension: json
    identifier_field: id
    fields:
      - { name: name, label: Name }
      - { name: path, label: Path }
      - label: 404 Page
        name: notfoundpage
        widget: object
        fields:
          - { name: pageImage, label: Page Image, widget: image, required: false}
          - {label: Image Title, name: attrTitle, widget: string, required: false}
          - {label: Author, name: attrAuthor, widget: string, required: false}
          - {label: Source Attribution URL, name: attrLink, widget: string, required: false}
          - {label: License, name: attrLicense, widget: string, required: false}
          - {label: Modifications, name: attrMods, widget: string, required: false}
      - label: Blog Page
        name: blogpage
        widget: object
        fields:
          - {label: Sort Type, name: sortType, widget: string, required: false}
          - label: About Bar
            name: aboutbar
            widget: object
            fields:
              - {label: Title, name: barTitle, widget: string, required: false}
              - {label: Body, name: barBody, widget: string, required: false}
      - label: Site Wide
        name: sitewide
        widget: object
        fields:
          - {label: Copyright, name: copyright, widget: string, required: false}